### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ric96** [Overv/vramfs#10]
ubuntu 16.04
gcc 4.9
nvidia gtx 960
clinfo: http://paste.ubuntu.com/23541229/
compile error: http://paste.ubuntu.com/23541234/

thnx!

**Comment by ric96** [comment]
It got rid of the "is depreciated" errors
but these errors are still present: http://paste.ubuntu.com/23545452/

**Comment by Overv** [comment]
Try adding `#undef CL_VERSION_1_2` at the top of `memory.cpp`, right below `#include "memory.hpp"`.

**Comment by ric96** [comment]
same errors still remain...

**Comment by ric96** [comment]
so its the same as
https://github.com/Overv/vramfs/issues/4

**Comment by ric96** [comment]
okay so reverting back to https://github.com/Overv/vramfs/commit/1bdcab10ff572059bc33cfc7568f7ce66d616130

and adding CFLAGS += -DCL_USE_DEPRECATED_OPENCL_1_2_APIS th the makefile solves the issue for me.

Awesome project btw!!!

**Comment by Overv** [comment]
@Oblomov Do you know why your changes are still causing errors?

**Comment by Oblomov** [comment]
The issue seems to arise from using the local `cl_1_1.hpp` when the system `cl.h` does support `CL_VERSION_1_2`. I cannot think of a sensible way to handle this relying on the `hpp` headers (mostly because they are _really_ bad overall, particularly the old ones).

One way would be to ship our own `cl.hpp`, up to date and able to properly discriminate between OpenCL versions, without even the need to call `make OPENCL_1_1` in the first place. The other way would be to not use the C++ interface (see my opinion on it above). And of course the real question is whether we still want to support compiling with the long obsolete 1.1 headers, considering even NVIDIA has finally introduced 1.2 support in the last year or so. If we really must still support using the old headers.

I can implement whichever approach you prefer, let me know and I'll issue a pull request in that sense.

**Comment by Overv** [comment]
NVIDIA was the only reason we were using < 2.0 in the first place, so it would be best to upgrade to 1.2.

**Comment by Oblomov** [comment]
OK, I'll submit a pull request to expunge the 1.1 support then.

**Comment by Oblomov** [comment]
I'm guessing this can be closed now that the 1.1 support removal has been merged in.
